# -*- coding: utf-8 -*-
"""Aula de pa 2 bimestre.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j_w2dPnFzU9o3t5slB5tiymekPcgwBOQ
"""

# iterações e laços de repetição

for i in range (5):
 print ("olá mundo!")

for i in range (6):
 print (i)

for i in range (1, 6):
  print(i)

# Escrever um programa que imprime de 5 até 0

for i in range (7):
  print (6-i)

# Escrever um programa que imprime os números pares de 0 a 10

for i in range (11):

  if i % 2 == 0:
    print (i)

# imprime números impares

for i in range (0,10,3):

  print(i)

# Escrever um programa que o usuário digita um número de 1 a 10 e imprime a tabuada
número = int (input("digite um número de 1 a 10:"))

for i in range (1,11):
  print (f"{número} x {i} = {número * i}")

# Escrever um programa que o usuário digita um número e o programa imprime de 0 até o número;

nm = int (input("digite um número:"))
num = nm + 1
for i in range (0,num):
  print(i)

# Escrever um programa que o usuário digita um número e o programa imprime em ordem decrescente
# até o zero

numero = int (input("digite um número"))

for i in range(numero,-1,-1):
    print(i)

# pede um número ao usuário
numero = int(input("Digite um número: "))

# mostra os números pares até esse número
print("Números pares até", numero, ":")

for i in range(0, numero + 1, 2):
    print(i)

# peça um número e calcule a soma de 1 até o número

numero = int(input("Digite um número: "))

soma = 0
for i in range(1, numero + 1):
    soma += i

print("A soma de 1 até", numero, "é:", soma)

# peça uma palavra e conte as letras: ex: python - a palavra tem 06 letras
palavra = input("Digite uma palavra: ")

quantidade = len(palavra)

print(f"A palavra '{palavra}' tem {quantidade:02d} letras")

# peça uma palavra e conte as vogais

vogais = "aeiou"
contador = 0

for letra in palavra:
    if letra in vogais:
        contador += 1

print(f"A palavra '{palavra}' tem {contador} vogais")

# peça ao usuário para digitar 05 números e informe o valor

numeros = []

for i in range(5):
    n = float(input(f"Digite o {i+1}º número: "))
    numeros.append(n)

soma = sum(numeros)

print("A soma dos números é:", soma)

# escrever um programa que o usuário digita um número de 1 a 10 e o programa imprime a tabuada do número digitado.

numero = int (input("digite um número de 1 a 10"))

for i in range (1,11):

  print (f"{numero} x {i} = {numero * i}")

# escrever um programa que o usuário digita um número e o programa imprime até o número digitado.

numero = int (input("digite um número"))

for i in range (11):

 print(f"{numero}")

# escrever um programa que o usuário digita um número e o programa imprime o número digitado até o zero (contagem regressiva)


numero = int (input("digite um número"))

for i in range(numero,-1,-1):
    print(i)

# escrever um programa que o usuário digita um número e o programa imprime os números pares
for i in range (11):

  if i % 2 == 0:
    print (i)

# escrever um programa que o suário digita um número e o programa imprime os números impares

for i in range (11):

  if i % 3 == 0:
    print (i)

# escrever um programa que o usuario digita um numero e o programa some os numeros ate o numero digitado

numero = int(input("Digite um número: "))

soma = 0
for i in range(1, numero + 1):
    soma += i

print(f"A soma dos números até {numero} é: {soma}")

# escrever um programa que o usuario digita 04 numeros e o programa imprime o valor

palavra = input("Digite uma palavra: ")
quantidade_letras = len(palavra)
print(f"A palavra '{palavra}' tem {quantidade_letras} letras.")

palavra = input("Digite uma palavra: ")
palavra_invertida = palavra[::-1]
print(f"A palavra invertida é: {palavra_invertida}")

# pirâmide numérica simétrica

# Faça um programa que receba um número N e imprima uma pirâmide perfeitamente centralizada.

# Exemplo para N = 5
#         1
#       2 1 2
#      3 2 1 3
#   4 3 2 1 2 3 4
#  5 4 3 2 1 3 4 5

def print_numeric_pyramid(N):
    # Determina a largura máxima da linha para centralização.
    # A linha mais longa é a última, e seus elementos são N ... 1 ... N.
    # Criamos uma string com a última linha para obter o comprimento correto.
    ultima_linha_elementos = [str(x) for x in range(N, 0, -1)] + [str(x) for x in range(2, N + 1)]
    largura_maxima = len(' '.join(ultima_linha_elementos))

    for i in range(1, N + 1):
        # Constrói a parte esquerda da linha (de i até 1)
        parte_esquerda = ' '.join(map(str, range(i, 0, -1)))

        # Constrói a parte direita da linha (de 2 até i, se i > 1)
        parte_direita = ''
        if i > 1:
            parte_direita = ' '.join(map(str, range(2, i + 1)))

        # Combina as partes esquerda e direita para formar a linha completa
        if parte_direita:
            linha_completa = f"{parte_esquerda} {parte_direita}"
        else:
            linha_completa = parte_esquerda

        # Centraliza a linha completa usando a largura_maxima calculada
        print(linha_completa.center(largura_maxima))

# Solicita o número N ao usuário e garante que seja um número inteiro positivo
while True:
    try:
        N = int(input("Digite um número inteiro positivo para N (ex: 5): "))
        if N > 0:
            break
        else:
            print("Por favor, digite um número maior que zero.")
    except ValueError:
        print("Entrada inválida. Por favor, digite um número inteiro.")

# Imprime a pirâmide
print_numeric_pyramid(N)